# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - vote/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e1d6b241-d3f0-43ea-9d1f-f80284ee1900'
  imageRepository: 'vote'
  containerRegistry: 'jhcicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
 name: 'vote'


stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'
- stage: push
  displayName: push
  jobs:
  - job: push
    displayName: push
    steps:
    - task: Docker@2
      displayName: push image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'
- stage: push
  displayName: push
  jobs:
  - job: push
    displayName: push
    steps:
- task: ShellScript@2
  inputs:
    scriptPath: 'scripts/updatek8smanifests.yaml'
    args: 'vote $imageRepository $ tag'